name: whos-in-charge-ifs
services:
- name: web
  source_dir: /
  github:
    repo: your-github-username/your-repo-name
    branch: main
  run_command: npm run preview
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  http_port: 8080
  build_command: npm run build
  catchall_document: index.html